added backup and restore

diff --git a/chef-infra b/chef-infra
--- a/chef-infra
+++ b/chef-infra
@@ -6,13 +6,15 @@
 # helper functions
 #
 usage() {
-  echo "Usage: $0 [setup|backup|restore|teardown] [options]"
+  echo "Usage: $0 [setup|build|backup|restore|teardown] [options]"
   echo ""
   echo "-h,--help    show this message"
   echo ""
   echo "setup options: Creat a local Chef Infrastructure"
-  echo "-c, --count Number of nodes to include in the fleet (default: 2)"
-  echo "-b, --build download and build packages only "
+  echo "-c, --count requires an integer. Number of nodes to include in the fleet (default: 2)"
+  echo ""
+  echo "build options: Compile binaries"
+  echo "-f, --force remove current packages and re-build"
   echo "-l, --local Create/overwrite local files only, create Vagrantfile,"
   echo "              knife.rb, cookbook upload, etc."
   echo ""
@@ -20,7 +22,8 @@ usage() {
   echo " none"
   echo ""
   echo "restore options: Restore to the latest backup, if one exists"
-  echo " none"
+  echo "-s, --server Path to Chef server backup (default: latest file)"
+  echo "-a, --automate Path to Automate backup (default: latest file)"
   echo ""
   echo "teardown options: Remove files and objects created"
   echo "-p,--pretend just list what will be done"
@@ -28,6 +31,13 @@ usage() {
   echo "             packages. For convienience and speed, these are not removed"
   echo "             by default."
   echo "-y,--yes     answer yes to all prompts"; exit 1;
+}
+
+do_error() {
+  echo ""
+  echo ""
+  echo "${RED}ERROR: ${1}${NC}"
+  exit 1
 }
 #
 # append to /etc/hosts file
@@ -170,9 +180,7 @@ Vagrant.configure(2) do |config|
       node.ssh.password = "vagrant"
       node.vm.provision "shell", inline: "echo 192.168.33.200 chef-server.test | sudo tee -a /etc/hosts"
       node.vm.provision "shell", inline: "echo 192.168.33.1#{i} #{node_id}.test | sudo tee -a /etc/hosts"
-      node.vm.provision "shell", inline: "sudo pacman -Sy --noconfirm wget binutils fakeroot cronie ntp"
-      # node.vm.provision "shell", inline: "sudo -H -u vagrant bash -c 'cd ${GUEST_WKDIR} && wget -N -nv https://aur.archlinux.org/cgit/aur.git/snapshot/chef-dk.tar.gz && tar -xvzf *.tar.gz'"
-      # node.vm.provision "shell", inline: "if [ \"\$(ls ${GUEST_WKDIR}/chef-dk/chef*xz)\" == \"\" ]; then sudo -H -u vagrant bash -c 'cd ${GUEST_WKDIR}/chef-dk && makepkg -s'; fi"
+      node.vm.provision "shell", inline: "sudo pacman -Sy --noconfirm fakeroot cronie ntp"
       node.vm.provision "shell", inline: "cd ${GUEST_WKDIR}/pkgs/chef-dk && sudo pacman -U --noconfirm *xz"
       node.vm.provision "shell", inline: "sudo mkdir -p /etc/chef && cat >/etc/chef/client.rb <<EOL
 log_level        :info
@@ -272,6 +280,17 @@ knife client delete \$1
 vagrant destroy \$1 -f
 EOL
   chmod +x rm-node
+}
+
+do_create() {
+  echo "Creating knife.rb..."
+  create_knife_rb
+  echo "Creating roles/base.rb..."
+  create_base_rb
+  echo "Creating Vagrantfile..."
+  create_vagrantfile 2>/dev/null
+  echo "Creating helper scripts..."
+  create_helpers
 }
 
 #
@@ -425,7 +444,7 @@ do_setup() {
   echo "*******************************************************************"
 }
 
-do_bkps() {
+do_backup() {
   echo "Begin taking backups..."
   d=`date '+%Y%m%d%H%M%S'`
   sudo mkdir -p ${GUEST_WKDIR}/bkps/srvr
@@ -433,14 +452,19 @@ do_bkps() {
   # backup chef server
   vagrant ssh srvr -c "sudo knife ssl fetch https://chef-server.test && sudo /opt/opscode/embedded/bin/knife ec backup ${GUEST_WKDIR}/bkps/srvr/${d} -s https://chef-server.test --user pivotal --key /etc/opscode/pivotal.pem"
   # backup automate
-  vagrant ssh a2 -c "sudo printf \"[global.v1.backups.filesystem]\npath = '${GUEST_WKDIR}/bkps/a2'\n\" > backup_config.toml && sudo ./chef-automate config patch backup_config.toml && sudo ./chef-automate backup create"
+  vagrant ssh a2 -c "if [ ! -f backup_config.toml ]; then sudo printf \"[global.v1.backups.filesystem]\npath = '${GUEST_WKDIR}/bkps/a2'\n\" > backup_config.toml && sudo ./chef-automate config patch backup_config.toml; fi && sudo ./chef-automate backup create"
   echo "Backups complete."
 }
 
-#do_restore() {
-  # TODO restore chef Server
-  # TODO restore automate
-#}
+do_restore() {
+  # restore chef Server
+  if [ $srvr_bak == "" ]; then srvr_bak=`ls -qaltr ./bkps/srvr| tail -1` ; fi
+  if [ $a2_bak == "" ]; then a2_bak=`ls -qaltr ./bkps/a2| tail -1` ; fi
+  if [ ! -d $srvr_bak ]; then do_error "Chef Server Backup does not exist. Look in ./bkps and try again." ; fi
+  if [ ! -d $a2_bak ]; then do_error "Automate Backup does not exist. Look in ./bkps and try again." ; fi
+  vagrant ssh srvr -c "sudo knife ssl fetch https://chef-server.test && sudo /opt/opscode/embedded/bin/knife ec restore ${GUEST_WKDIR}/bkps/srvr/${srvr_bak} -s https://chef-server.test --user pivotal --key /etc/opscode/pivotal.pem"
+  vagrant ssh a2 -c "sudo ./chef-automate backup restore $a2_bak"
+}
 
 do_teardown() {
   echo "Begin Chef Infrastructure teardown"
@@ -504,158 +528,113 @@ do_teardown() {
   echo "Teardown of Chef Infrastructure complete. Thanks for playing... :)"
 }
 
-#TODO refactor arguments with getops
 #
 # Begin chef-infra.sh
 #
 # initalize default flags
-#is_setup=false
-#is_local=false
-#is_compile=false
-#is_bkps=false
-#is_rest=false
-#is_teardown=false
 cnt=2
 is_full=false
 is_yes=false
 is_pre=false
 
-#for i in "$@"
-#do
-#case $i in
-#    is_setup=true
-#    ;;
-#    teardown)
-#    is_teardown=true
-#    ;;
-#    -l|--local)
-#    is_local=true
-#    ;;
-#    -c|--compile)
-#    is_compile=true
-#    ;;
-#    -b|--backup)
-#    is_bkps=true
-#    ;;
-#    -r|--restore)
-#    is_rest=true
-#    ;;
-#    -f|--full)
-#    is_full=true
-#    ;;
-#    -y|--yes)
-#    -p|--pretend)
-#    is_pre=true
-#    ;;
-#    -h|--help)
-#    usage
-#    ;;
-#    *)
-#    usage
-#    ;;
-#esac
-#done
 # record and print elapsed time
 start=`date +%s`
 
 # parse first argument
 case $1 in
   setup)
-    while getopts ":l:b:c:h:" o; do
+    shift
+    while getopts ":c:h" o; do
       case $o in
-        l|local)
-          create_only
-          ;;
-        b|build)
-          create_vagrantfile 2>/dev/null
-          do_compile
-          ;;
-        c|count)
+        c|count )
           cnt=$OPTARG
           echo "Create $cnt nodes"
           ;;
-        h|help)
+        h|help )
           usage
           ;;
-        *)
-          do_node_setup
+        * )
+          usage
           ;;
       esac
     done
+    do_setup
     ;;
-  backup)
-    do_backup
-    ;;
-  restore)
-    do_restore
-    ;;
-  teardown)
-    while getopts ":p:y:f:h:" o; do
+  build )
+    shift
+    while getopts ":flh" o; do
       case $o in
-        p|pretend)
-          is_pre=true
+        f|force )
+          rm -rf ./pkgs
           ;;
-        y|yes)
-          is_yes=true
+        l|local )
+          do_create
           ;;
-        f|full)
-          is_full=true
-          ;;
-        h|help)
+        h|help )
           usage
           ;;
-        *)
+        * )
+          usage
+          ;;
+      esac
+    done
+    create_vagrantfile 2>/dev/null
+    do_compile
+    ;;
+  backup )
+    shift
+    do_backup
+    ;;
+  restore )
+    shift
+    while getopts ":s:a:h" o; do
+      case $o in
+        s|server )
+          srvr_bak=$OPTARG
+          shift
+          ;;
+        a|automate )
+          a2_bak=$OPTARG
+          shift
+          ;;
+        h|help )
+          usage
+          ;;
+        * )
+          usage
+          ;;
+      esac
+    done
+    do_restore
+    ;;
+  teardown )
+    shift
+    while getopts ":pyfh" o; do
+      case $o in
+        p|pretend )
+          is_pre=true
+          ;;
+        y|yes )
+          is_yes=true
+          ;;
+        f|full )
+          is_full=true
+          ;;
+        h|help )
+          usage
+          ;;
+        * )
           ;;
       esac
     done
     do_teardown
     ;;
-  *)
+  * )
     usage
     ;;
 esac
 
-#if [ $is_setup == $is_teardown ] ;
-#then
-#  echo " "
-#  echo -e "${RED}Error: specify one task, setup or teardown${NC}"
-#  echo " "
-#  usage
-#elif $is_setup ;
-#then
-#  if $is_local ;
-#  then
-#    echo "Creating knife.rb..."
-#    create_knife_rb
-#    echo "Creating roles/base.rb..."
-#    create_base_rb
-#    echo "Creating Vagrantfile..."
-#    create_vagrantfile 2>/dev/null
-#    echo "Creating helper scripts..."
-#    create_helpers
-#  elif $is_compile ;
-#  then
-#    create_vagrantfile 2>/dev/null
-#    do_compile
-#  elif $is_bkps ;
-#  then
-#    do_bkps
-#  elif $is_rest ;
-#  then
-#    do_restore
-#  else
-#    do_setup
-#  fi
-#elif $is_teardown ;
-#then
-#  do_teardown
-#else
-#  echo " "
-#  echo -e "${RED}Error: specify one task, setup or teardown${NC}"
-#  echo " "
-#  usage
-#fi
-
+# finish up with some metrics
 end=`date +%s`
 runtime=$((end-start))
 echo ""
